name: Docker Image CI

on:
  push:
    branches: ["preproduction"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: Build and push image
        working-directory: ./sources/backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/library.gateway -f ./LibraryServices.Gateway/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/library.gateway
