name: Docker Image CI

on:
  push:
    branches: ["preproduction"]
  pull_request:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: Build and push image
        working-directory: ./sources/backend
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker build -t $USERNAME/library.gateway -f ./LibraryServices.Gateway/Dockerfile .
          docker push $USERNAME/library.gateway

          docker build -t $USERNAME/library.family -f ./LibraryServices.FamilyService/Dockerfile .
          docker push $USERNAME/library.family          

          docker build -t $USERNAME/library.identity -f ./LibraryServices.IdentityService/Dockerfile .
          docker push $USERNAME/library.identity

          docker build -t $USERNAME/library.package -f ./LibraryServices.PackageService/Dockerfile .
          docker push $USERNAME/library.package

          docker build -t $USERNAME/library.parameter -f ./LibraryServices.ParameterService/Dockerfile .
          docker push $USERNAME/library.parameter
